version: 0.0
os: linux
files:
  - source: "/"
    destination: /var/www/spacemaster-web
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/dependencyInstall.sh
      timeout: 500
      runas: ec2-user
  ApplicationStart:
    - location: scripts/applicationStart.sh
      timeout: 300
      runas: ec2-user